[tool.poetry]
name = "travelbot"
version = "0.1.0"
description = ""
authors = ["Maria Tenetko"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
telebot = "^0.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
